### ISSUE TITLE
Error: Cannot find module './secretGitIgnore'

### ISSUE THREAD

**Issue by Kekson** [bumbeishvili/fb-github-trends#1]
I have a problem with secretGitIgnore.js there is no such file in your repository,  can you please upload an example of this file ?

**Comment by bumbeishvili** [comment]
This file contains sensitive information : (db connection string and fb page access tokens)
This is how it looks, you should replace it with you data
![screen shot 2018-02-22 at 21 08 03](https://user-images.githubusercontent.com/6873202/36553069-d4a8e6d0-1814-11e8-9e27-b9bafa9ef00c.png)
